global:
  scrape_interval: 5s
  scrape_timeout: 4s

rule_files:
  - /etc/prometheus/alerts.yaml

scrape_configs:
  - job_name: chainflip-prometheus-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9000"
