name: ci-main
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  pre-check:
    uses: ./.github/workflows/_00_pre_check.yml
  build:
    needs: [pre-check]
    uses: ./.github/workflows/_01_docker.yml
